#!/bin/bash -e

gsettings set org.yorba.shotwell.preferences.ui show-welcome-dialog false
gsettings set org.yorba.shotwell.preferences.files auto-import true

PICTURES_DIR=~endlessm/$(gettext -d xdg-user-dirs Pictures)
mkdir -p $PICTURES_DIR
cp -r /usr/share/endlessm/default_images/* $PICTURES_DIR
chown -R endlessm:endlessm $PICTURES_DIR

