#!/bin/bash -e

gsettings set org.yorba.shotwell.preferences.ui show-welcome-dialog false
if [[ "false" != $(gsettings get org.yorba.shotwell.preferences.ui show-welcome-dialog) ]]
then
	exit 1
fi

gsettings set org.yorba.shotwell.preferences.files auto-import true
if [[ "true" != $(gsettings get org.yorba.shotwell.preferences.files auto-import) ]]
then
	exit 1
fi

PICTURES_DIR=~endlessm/$(gettext -d xdg-user-dirs Pictures)
mkdir -p $PICTURES_DIR
cp -r /usr/share/endlessm/default_images/* $PICTURES_DIR
chown -R endlessm:endlessm $PICTURES_DIR

